### ISSUE TITLE
Missing loader

### ISSUE THREAD

**Issue by m3talsmith** [RickCarlino/mud#1]
➜  mud git:(master) ruby lib/mud.rb
lib/mud.rb:1:in `require_relative': no such file to load -- /Users/mchristenson/projects/mud/lib/loader (LoadError)
    from lib/mud.rb:1:in`<main>'

**Comment by RickCarlino** [comment]
Whoops! Forgot to add the loader to source control and as such it never made it on to Github. Try again.
