### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by swilliams** [RickCarlino/mud#2]
Noticed that most of the files in here aren't documented. Ruby has a couple of pretty nice tools for documentation like [sdoc](https://github.com/voloko/sdoc).

Documentation is important for several reasons, as [listed here](http://zachholman.com/posts/documentation/).

(lulz)

**Comment by RickCarlino** [comment]
This guy ^

**Comment by RickCarlino** [comment]
There. But only because I'm feeling spiteful.

**Comment by swilliams** [comment]
Giant LOL. I love you too.
