### ISSUE TITLE
Documentation doesn't explain how to use sessions, controllers or connections

### ISSUE THREAD

**Issue by Portalboy** [RickCarlino/mud#4]
First off I understand that this is a toy and that you have bigger fish to fry. I can wait.

Currently the Tutorial code snippet, when run, just gives the `'Press enter to exit'` message. A server is being defined, but there is no session, connection or controller instantiated.
I'm currently crawling over the code trying to beat it to life, but I'm having a really hard time.

**Comment by Portalboy** [comment]
As an example, adding `session = MudServer::Session.new(server)` and running returns the following:

```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-mud-0.0.4/lib/session.rb:12:in `bootstrap_settings': undefined method `peeraddr' for #<MudServer:0x00000002ef1878> (NoMethodError)
    from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-mud-0.0.4/lib/session.rb:6:in `initialize'
    from C:/Users/Joshua.Murphy/RubymineProjects/FirstMUD/tester.rb:59:in `new'
    from C:/Users/Joshua.Murphy/RubymineProjects/FirstMUD/tester.rb:59:in `<top (required)>'
    from -e:1:in `load'
    from -e:1:in `<main>'
```

P.S. I've also tried this outside of RubyMine IDE

**Comment by Portalboy** [comment]
Just tried using the `net-telnet` gem to open a Telnet connection to the instantiated `MudServer`, got the same `peeraddr` error as above when using it as the `connection` parameter for the `session` constructor

**Comment by RickCarlino** [comment]
It don't think `peeraddr` is available in later versions of Ruby's `TCPServer`. There are no mentions of it here: https://ruby-doc.org/stdlib-2.3.0/libdoc/socket/rdoc/TCPServer.html whereas there _are_ mentions of it here, in an outdated version of Ruby: https://ruby-doc.org/stdlib-1.9.3/libdoc/socket/rdoc/IPSocket.html

So it looks like this gem (probably) does not support Ruby 2.3.

**Comment by Portalboy** [comment]
Oh well, it was worth a shot 😢 

Thank you for your speedy reply!
